### ISSUE TITLE
你好，项目在运行过程中报错

### ISSUE THREAD

**Issue by pythonlw** [yaochao/NetEaseMusicCrawler#3]
刚开始报的是KeyError: 'driver'，我在downloadhandlers.py中return dfd加了driver（return dfd,driver），没有报这个错了，然后又报AttributeError: 'tuple' object has no attribute 'status'
Traceback (most recent call last):
  File "C:\Users\Administrator.PC-20170610UEYX\AppData\Local\Programs\Python\Python35\lib\site-packages\twisted\internet\defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "C:\Users\Administrator.PC-20170610UEYX\AppData\Local\Programs\Python\Python35\lib\site-packages\scrapy\core\downloader\middleware.py", line 53, in process_response
    spider=spider)
  File "C:\Users\Administrator.PC-20170610UEYX\AppData\Local\Programs\Python\Python35\lib\site-packages\scrapy\downloadermiddlewares\stats.py", line 26, in process_response
    self.stats.inc_value('downloader/response_status_count/%s' % response.status, spider=spider)
AttributeError: 'tuple' object has no attribute 'status'

**Comment by pythonlw** [comment]
问题已解决，不应该加driver
